#MYSQL配置
MySQL_IP: localhost
MySQL_port: 3306
MySQL_database: XXXXX
MySQL_Table: XXXXX
MySQL_user: XXXXX
MySQL_password: XXXXX

#用于区分，不要与其他容器标题相同
Title: liert
#Lore
iloSpLore: "梦都饰品"

Msg: "§7[§a梦都饰品§7]§c $item §a激活成功"
ActivateMsg: "§7[§a梦都饰品§7]§c $item §a已激活，请勿重复放入！"
LimitMsg: "§7[§a梦都饰品§7]§c $item §a数量过多！"