#MYSQL配置
MySQL_IP: localhost
MySQL_port: 3306
MySQL_database: XXXXX
MySQL_Table: XXXXX
MySQL_user: XXXXX
MySQL_password: XXXXX

# 饰品背包容量
Max: 54

#用于区分，不要与其他容器标题相同
Title: liert
#Lore
iloSpLore: "梦都饰品"
